### ISSUE TITLE
HCUSTOMMODULE undeclared

### ISSUE THREAD

**Issue by hafedh-trimeche** [Fr0sT-Brutal/Delphi_MemoryModule#3]
Undeclared HCUSTOMMODULE (old declaration HMODULE)

**Comment by hafedh-trimeche** [comment]
https://github.com/Fr0sT-Brutal/Delphi_MemoryModule/blob/master/MemoryModule.pas
at line 148

**Comment by Fr0sT-Brutal** [comment]
Yep, sure. Fixed that. Could you test `dev` branch as well?
